- name: ntp
  src: geerlingguy.ntp
  version: 1.6.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.6

- name: docker
  src: nickjj.docker
  version: v1.2.0
