apt_packages_default:
  python-software-properties: "{{ apt_package_state }}"
  python-pycurl: "{{ apt_package_state }}"
  build-essential: "{{ apt_package_state }}"
  python-mysqldb: "{{ apt_package_state }}"
  curl: "{{ apt_package_state }}"
  git: "{{ apt_package_state }}"
  dbus: "{{ apt_package_state }}"
  libnss-myhostname: "{{ apt_package_state }}"

apt_packages_custom: {}
apt_packages: "{{ apt_packages_default | combine(apt_packages_custom) }}"
